### PR TITLE
On branch edburns-msft-gh-69-dd-1429446-remediation-actions-failed-certification See https://oracle-ama.visualstudio.com/marketplacesolutions/_git/oracle/pullrequest/2

### PR DESCRIPTION
**Pull request by edburns**
…
modified:   weblogic-azure-aks/pom.xml

- Increment version.

modified:   weblogic-azure-aks/src/main/arm/createUiDefinition.json

- Add toolTip where possible.

- Add regex length constraint where possible.

- Force the user to paste the base64 string twice. I wouldrather not
  ask the user this, but I don't want to haggle with the test administrators.

- Added output for `dropDownTargets`.  Temporarily pass to `mainTemplate` but just fo outputting.

modified:   weblogic-azure-aks/src/main/bicep/mainTemplate.bicep

- made `dbPassword` a secure string.

- Accept `dropdownTargets`  from createUiDefinition, but just output the length.

modified:   weblogic-azure-aks/src/main/bicep/modules/_azure-resoruces/_acr.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/_azure-resoruces/_aks.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/_azure-resoruces/_storage.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/_deployment-scripts/_ds-create-networking.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/_deployment-scripts/_ds-create-wls-cluster.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/networking.bicep
modified:   weblogic-azure-aks/src/main/bicep/modules/setupWebLogicCluster.bicep

- Do not hard code `location`.

Signed-off-by: Ed Burns <edburns@microsoft.com>

### CODE REVIEW

**Comment by edburns** [comment]
Fixes #69 .

**Comment by edburns** [comment]
I request review from @galiacheng .

**Comment by galiacheng** [comment]
Hello @edburns a successful run: https://github.com/galiacheng/weblogic-azure/actions/runs/1415130295
I think the pr is ready to merge.

**Comment by galiacheng** [comment]
Hello Ed, I fixed some exception that arm-ttk fired, please have a look at the changes. 
I am running the pipeline in https://github.com/galiacheng/weblogic-azure/actions/runs/1416164777
Also deployed a resource in [haiche-test-1](https://portal.azure.com/?feature.customPortal=false#@microsoft.onmicrosoft.com/resource/subscriptions/05887623-95c5-4e50-a71c-6e1c738794e2/resourceGroups/haiche-test-1/overview)

**Review by edburns — COMMENTED** [review]
Reviewed @galiacheng  commits from 2021-11-03. Approved.

**Comment by edburns** [comment]
Successful run at https://github.com/edburns/weblogic-azure/actions/runs/1417736010 .

**Review by mriccell — APPROVED** [review]

**Pull request merged**
