### PR TITLE
Configure Bicep Apiversions with properties file

### PR DESCRIPTION
**Pull request by backwind1233**
## Context
Refer to https://github.com/oracle/weblogic-azure/pull/278

## Changes and improvements.

1. Update workflow to get artifactid versions. Thanks for the advice from  @majguo.
    ``` 
    mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec
    ```
3. Use `azure-common.properties` to place all apiversions, include bicep files.
   - Extract ApiVersions in `microsoft-pid.properties` and `pid.properties`.
4. Code Refactor
   - Place all properties in root [pom.xml](https://github.com/oracle/weblogic-azure/blob/ac28258a1bf69053b8b581ac9fbd0a499c888f22/weblogic-azure-vm/pom.xml#L27). 
   - Use file pattern instead of url pattern, check [link](https://github.com/oracle/weblogic-azure/blob/ac28258a1bf69053b8b581ac9fbd0a499c888f22/weblogic-azure-vm/pom.xml#L33).

## Check the generated offer zip file
1. Download the [wls-on-aks-azure-marketplace-1.0.64-arm-assembly](https://github.com/azure-javaee/weblogic-azure/suites/16356462196/artifacts/934272234).
3. Unzip the file.
4. Check the `mainTemplate.json` to make sure it contains the right versions. ✅
image

# Test Results

✅ Both workflow and local tests passed.

## Test AKS ✅

```jsx
mvn -Pbicep -Passembly clean install -Ptemplate-validation-tests --file weblogic-azure/weblogic-azure-aks/pom.xml

# ---
# BUILD SUCCESS
```

## Test admin ✅

```jsx
cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-admin
  pidType=oracle
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pid"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pid"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi

# ---
# BUILD SUCCESS

cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-admin
  pidType=non-oracle
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pid"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pid"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi

# ---
# BUILD SUCCESS
```

## Test cluster✅

```jsx
cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster
  pidType=oracle
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pid"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pid"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi

# ---
# BUILD SUCCESS

cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-cluster/arm-oraclelinux-wls-cluster
  pidType=non-oracle
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pid"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pid"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi

# ---
# BUILD SUCCESS
```

## Test dynamic-cluster✅

```jsx
cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster
  pidType=oracle
  echo ${pidType}
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pids"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pids"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi

# ---
# BUILD SUCCESS

cd weblogic-azure/weblogic-azure-vm/arm-oraclelinux-wls-dynamic-cluster/arm-oraclelinux-wls-dynamic-cluster
  pidType=non-oracle
  echo ${pidType}
  if [[ "${pidType}" == "oracle" ]];then
    echo "using oracle pids"
    mvn -Ptemplate-validation-tests clean install -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  else
    echo "using ms pids"
    mvn -Ptemplate-validation-tests clean install -Ddev -Dgit.repo.owner=azure-javaee -Dgit.tag=refs/heads/bicep_apiversion_with_properties
  fi
# ---
# BUILD SUCCESS
```

## Workflow test

| Type                      | Workflow                                                     | Result |
| ------------------------- | ------------------------------------------------------------ | ------ |
| AKS                       | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244945897 | ✅      |
| admin-oracle              | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244959219 | ✅      |
| admin-microsoft           | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244955669 | ✅      |
| cluster-oracle            | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244965523 | ✅      |
| cluster-microsoft         | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244962211 | ✅      |
| dynamic-cluster-oracle    | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244972123 | ✅      |
| dynamic-cluster-microsoft | https://github.com/azure-javaee/weblogic-azure/actions/runs/6244969344 | ✅      |

### CODE REVIEW

**Comment by backwind1233** [comment]
Hello @edburns, please help review this PR.

**Comment by backwind1233** [comment]
## Updates
When test all the preview offers ,there are error in two Cluster offers.

Offers | Test Result
-- | --
WebLogic Server on AKS | Deploy Success
Oracle WebLogic Server Cluster | Failed
Oracle WebLogic Server Dynamic Cluster | Failed
Oracle WebLogic Server with Admin Server | Deploy Success
Oracle WebLogic Server Single Node | Deploy Success


The error log is 



### Root Cause
The API Version replaceholders(eg: ${azure.apiVersionForPublicIPAddresses}) can be used in two in two scenarios
Scenario1: one for the definition of resources 
Scenario2:  the other for the reference of resources.
This [commit](https://github.com/oracle/weblogic-azure/pull/279/commits/2be175752a8eb0ab381ef6f382cd1b20db1c147b) is meant to fix a bug caused by incorrect resource referencing(Scenario2).

**Comment by backwind1233** [comment]
## Update
---
## All preview offer tests passed.


Offers | Test Result
-- | --
WebLogic Server on AKS | Deploy Success
Oracle WebLogic Server Cluster | Deploy Success
Oracle WebLogic Server Dynamic Cluster | Deploy Success
Oracle WebLogic Server with Admin Server | Deploy Success
Oracle WebLogic Server Single Node | Deploy Success

**Review by edburns — APPROVED** [review]

**Review by edburns — CHANGES_REQUESTED** [review]
I still am not able to observer a successful deployment with these changes for cluster or dynamic cluster. So, I am removing my approval. See https://dev.azure.com/weblogic-azure/Open%20Standard%20Enterprise%20Java%20(Java%20EE)%20on%20Azure/_workitems/edit/154

**Comment by edburns** [comment]
I need to be able to see a successful deployment from these preview offers before I can approve this:

- https://portal.azure.com/#create/oracle.20191007-arm-oraclelinux-wls-cluster-preview20191007-arm-oraclelinux-wls-cluster
- https://portal.azure.com/#create/oracle.20191021-arm-oraclelinux-wls-dynamic-cluster-preview20191021-arm-oraclelinux-wls-dynamic-cluster

**Comment by edburns** [comment]
Ok, I have now seen a successful deployment of all the VM offers and the AKS offer. I am re-approving this PR.

**Review by edburns — APPROVED** [review]

**Pull request merged**
