### PR TITLE
Output WLS image model and domain description

### PR DESCRIPTION
**Pull request by galiacheng**
This ps is to:

Add deployment output
-----------------
- image model
- image properties
- domain description

As the limitation of ARM template, multi-lines output is not supported,  this pr outputs shell commands, which decode the based64 string of YAML files to a file.

Add labels to the load balance service and ingress.
---------------------
| Targets | Labels for Load Balancer Service (for TCP/T3) | Labels for Ingress (for HTTP/HTTPS) |
|---------|---------|---------|
| admin server | weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`admin-server` <br /> azure.weblogc.createdByWlsOffer=`true` | weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`admin-server` <br /> azure.weblogc.createdByWlsOffer=`true` |
| admin server t3 |  weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`admin-server-t3-channel` <br /> azure.weblogc.createdByWlsOffer=`true` | -- |
| admin server remote console  | use the same service with admin console. | weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`admin-server-remote-console` <br /> azure.weblogc.createdByWlsOffer=`true` |
| cluster | weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`cluster-1` <br /> azure.weblogc.createdByWlsOffer=`true` | weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`cluster-1` <br /> azure.weblogc.createdByWlsOffer=`true` |
| admin server t3 |  weblogic.domainUID=`<domain-uid>`  <br /> azure.weblogic.target=`cluster-1-t3-channel` <br /> azure.weblogc.createdByWlsOffer=`true` | -- |

### CODE REVIEW

**Comment by galiacheng** [comment]
Successful run: https://github.com/galiacheng/weblogic-azure/actions/runs/1407377237

**Comment by galiacheng** [comment]
Resolved conflicts.

**Comment by galiacheng** [comment]
Successful run: https://github.com/galiacheng/weblogic-azure/actions/runs/1410825010

**Review by edburns — APPROVED** [review]
This PR has many changes, but I have tested them and corrected the problems I found. I approve.

**Comment by galiacheng** [comment]
Hello @edburns  I add a commit to out put the commands to connect aks.

**Comment by galiacheng** [comment]
Verify in https://github.com/galiacheng/weblogic-azure/runs/4350294216?check_suite_focus=true

**Comment by galiacheng** [comment]
Verify on https://github.com/galiacheng/weblogic-azure/actions/runs/1518806637

**Review by mriccell — APPROVED** [review]

**Pull request merged**
