### PR TITLE
Issue#155 modify custom extension script to handle jdbc driver updates

### PR DESCRIPTION
**Pull request by gnsuryan**

### CODE REVIEW

**Comment by sanjaymantoor** [comment]
Reviewed and tested the change. Changes made working fine.

**Review by jacobt123 — APPROVED** [review]
@mriccell please merge these changes. Thanks !

**Comment by edburns** [comment]
Pom versions need to be incremented.

**Comment by gnsuryan** [comment]
pom.xml files have been updated to increment the versions for admin, cluster & dynamic cluster offers.

**Review by mriccell — APPROVED** [review]

**Pull request merged**
